/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ProseLi: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/prose/Li.vue')['default']
    ProseUl: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/prose/Ul.vue')['default']
    UAlert: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UAvatar: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UContainer: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UDropdownMenu: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFooter: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UFooterColumns: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue')['default']
    UForm: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULink: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/vue/overrides/inertia/Link.vue')['default']
    UMarquee: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue')['default']
    UNavigationMenu: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageCard: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPageCTA: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue')['default']
    UPageList: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue')['default']
    UPageSection: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue')['default']
    USeparator: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    UTextarea: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    UUser: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/User.vue')['default']
  }
}
